# Generated by Django 3.2.5 on 2021-08-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='UniversityClass',
        ),
    ]
