name: Linting

on: [push, pull_request]

jobs:
  build:
    name: CI workflow
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      - name: Linting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_PYLINT: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
